export const THEMES = {
  light: {
    name: 'Light Mode',
    navbarMode: 'light',
    bg: '#ffffff',
    text: '#194340',
    textareaBg: '#ffffff',
    textareaText: '#194340',
    textareaBorder: '#ced4da',
    buttonBg: '#0d6efd',
    buttonHover: '#0b5ed7',
    buttonText: '#ffffff',
  },
  grey: {
    name: 'Grey Dark Mode',
    navbarMode: 'dark',
    bg: 'hsla(0, 0%, 22%, 0.95)',
    text: 'hsl(192, 29%, 97%)',
    textareaBg: '#383838',
    textareaText: '#ffffff',
    textareaBorder: '#b9c2c8',
    buttonBg: '#151515',
    buttonHover: '#c7cfd0',
    buttonText: '#e1e1f2',
    
  },
  olive: {
    name: 'Olive Dark Mode',
    navbarMode: 'dark',
    bg: '#808000',
    text: '#eaeaea',
    textareaBg: '#515824',
    textareaText: '#f5f5f5',
    textareaBorder: '#555652',
    buttonBg: '#2b300e',
    buttonHover: '#a8b2d1',
    buttonText: '#fff5e6',
  },
  red: {
    name: 'Red Dark Mode',
    navbarMode: 'dark',
    bg: '#4f0707',
    text: '#ffe8e8',
    textareaBg: '#971616',
    textareaText: '#fff5f5',
    textareaBorder: '#5c2020',
    buttonBg: '#1c0204',
    buttonHover: '#ff4d5a',
    buttonText: '#ffffff',
  },
  green: {
    name: 'Green Dark Mode',
    navbarMode: 'dark',
    bg: '#0a1f14',
    text: '#e8fff0',
    textareaBg: '#143d28',
    textareaText: '#f0fff5',
    textareaBorder: '#1f5c3a',
    buttonBg: '#136b43',
    buttonHover: '#40916c',
    buttonText: '#ffffff',
  },
  blue: {
    name: 'Blue Dark Mode',
    navbarMode: 'dark',
    bg: '#0a1628',
    text: '#e8f4ff',
    textareaBg: '#122a4a',
    textareaText: '#f0f8ff',
    textareaBorder: '#1e4a7a',
    buttonBg: '#04627e',
    buttonHover: '#72d7f5',
    buttonText: '#0a1628',
  },
};
