export const THEMES = {
  light: {
    name: 'Light Mode',
    navbarMode: 'light',
    bg: '#ffffff',
    text: '#194340',
    textareaBg: '#ffffff',
    textareaText: '#194340',
    textareaBorder: '#ced4da',
    buttonBg: '#0d6efd',
    buttonHover: '#0b5ed7',
    buttonText: '#ffffff',
  },
  dark: {
    name: 'Dark Mode',
    navbarMode: 'dark',
    bg: '#080708ef',
    text: '#ffffff',
    textareaBg: '#333638',
    textareaText: '#ffffff',
    textareaBorder: '#b9c2c8',
    buttonBg: '#547077',
    buttonHover: '#c7cfd0',
    buttonText: '#042743',
  },
  grey: {
    name: 'Grey Dark Mode',
    navbarMode: 'dark',
    bg: '#1f1f20',
    text: '#eaeaea',
    textareaBg: '#343b48',
    textareaText: '#f5f5f5',
    textareaBorder: '#3a3a5c',
    buttonBg: '#4d5f95',
    buttonHover: '#a8b2d1',
    buttonText: '#1a1a2e',
  },
  red: {
    name: 'Red Dark Mode',
    navbarMode: 'dark',
    bg: '#471717',
    text: '#ffe8e8',
    textareaBg: '#2d1212',
    textareaText: '#fff5f5',
    textareaBorder: '#5c2020',
    buttonBg: '#b32d38',
    buttonHover: '#ff4d5a',
    buttonText: '#ffffff',
  },
  green: {
    name: 'Green Dark Mode',
    navbarMode: 'dark',
    bg: '#0a1f14',
    text: '#e8fff0',
    textareaBg: '#143d28',
    textareaText: '#f0fff5',
    textareaBorder: '#1f5c3a',
    buttonBg: '#136b43',
    buttonHover: '#40916c',
    buttonText: '#ffffff',
  },
  blue: {
    name: 'Blue Dark Mode',
    navbarMode: 'dark',
    bg: '#0a1628',
    text: '#e8f4ff',
    textareaBg: '#122a4a',
    textareaText: '#f0f8ff',
    textareaBorder: '#1e4a7a',
    buttonBg: '#04627e',
    buttonHover: '#72d7f5',
    buttonText: '#0a1628',
  },
};
